version: "3"

services:
  neo4j:
    container_name: Neo4j-test
    image: neo4j:4.2.0
    volumes:
      - ./compose-data/neo4j/data:/data
      - ./compose-data/neo4j/plugins:/plugins
      - ./compose-data/neo4j/import:/import
    ports:
      - "17474:7474"
      - "17687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/docker
    networks:
      - "Neo4j-test"
volumes:
  Neo4j-test:
networks:
  Neo4j-test: