spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: docker
      open-in-view: false
      use-native-types: true
    rest:
      base-path: /v1/resources
  tomcat:
    relaxed-query-chars:
      - "["
      - "]"

server:
  error:
    include-message: always