spring:
  data:
    neo4j:
      uri: bolt://localhost:17687
      username: neo4j
      password: docker
      open-in-view: false
      use-native-types: true
    rest:
      base-path: /v1/resources

server:
  error:
    include-message: always


git:
  username:
  password:
  repos-path: ./repos

initial-user:
  login: admin
  password: admin

pcontrol:
  neo4j:
    indexes:
      USER: CALL db.index.fulltext.createNodeIndex("%", ["User"],["name"])
    constraints:
      - CREATE CONSTRAINT ON (user:AuthUser) ASSERT user.login IS UNIQUE


logging:
  level:
    com.valb3r.projectcontrol: INFO

oauth2:
  keys:
    # You should override these!
    pub: classpath:example.pub
    priv: classpath:example.pem
  validity: PT1H

bcrypt:
  strength: 8