/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitRepo } from './gitRepo';
import { Alias } from './alias';
import { Link } from './link';


export interface EntityModelTotalOwnershipStats { 
    repo?: GitRepo;
    alias?: Alias;
    id?: number;
    from?: string;
    to?: string;
    linesOwned?: number;
    _links?: { [key: string]: Link; };
}

