/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitRepo } from './gitRepo';
import { Alias } from './alias';
import { RemovedLines } from './removedLines';
import { Link } from './link';


export interface EntityModelWeeklyCommitStats { 
    repo?: GitRepo;
    alias?: Alias;
    from?: string;
    to?: string;
    commitCount?: number;
    linesAdded?: number;
    linesRemoved?: number;
    id?: number;
    linesRemovedOf?: Array<RemovedLines>;
    _links?: { [key: string]: Link; };
}

