/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


export interface EntityModelGitRepo { 
    id?: number;
    name?: string;
    branchToAnalyze?: string;
    url?: string;
    uuid?: string;
    needsAuthentication?: boolean;
    startFromCommit?: string;
    workDoneBySteps?: Array<string>;
    analysisState?: EntityModelGitRepo.AnalysisStateEnum;
    commitsProcessed?: number;
    errorMessage?: string;
    lastAnalyzedCommit?: string;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelGitRepo {
    export type AnalysisStateEnum = 'NONE' | 'CLEANUP' | 'CLEANED' | 'STARTED' | 'CLONING' | 'CLONED' | 'CHURN_COUNTING' | 'CHURN_COUNTED' | 'LOC_OWNERSHIP_COUNTING' | 'LOC_OWNERSHIP_COUNTED' | 'REFACTOR_COUNTING' | 'REFACTOR_COUNTED' | 'FINISHED' | 'FAILED';
    export const AnalysisStateEnum = {
        None: 'NONE' as AnalysisStateEnum,
        Cleanup: 'CLEANUP' as AnalysisStateEnum,
        Cleaned: 'CLEANED' as AnalysisStateEnum,
        Started: 'STARTED' as AnalysisStateEnum,
        Cloning: 'CLONING' as AnalysisStateEnum,
        Cloned: 'CLONED' as AnalysisStateEnum,
        ChurnCounting: 'CHURN_COUNTING' as AnalysisStateEnum,
        ChurnCounted: 'CHURN_COUNTED' as AnalysisStateEnum,
        LocOwnershipCounting: 'LOC_OWNERSHIP_COUNTING' as AnalysisStateEnum,
        LocOwnershipCounted: 'LOC_OWNERSHIP_COUNTED' as AnalysisStateEnum,
        RefactorCounting: 'REFACTOR_COUNTING' as AnalysisStateEnum,
        RefactorCounted: 'REFACTOR_COUNTED' as AnalysisStateEnum,
        Finished: 'FINISHED' as AnalysisStateEnum,
        Failed: 'FAILED' as AnalysisStateEnum
    };
}


